### ISSUE TITLE
ERROR:Install MotioninJoy Driver fail.. Error code:0X-1ffffdb5

### ISSUE THREAD

**Issue by sliatecinos** [XPanniX/MotioninJoyOffline#2]
Hello @XPanniX !
I'm getting this error when I try to install the driver on the USB port, even after restarting the computer:

![MotionInJoy 2020-12-26 165417](https://user-images.githubusercontent.com/13358191/103158320-2ddea100-479b-11eb-8912-131374bb711f.png)

Why does it happen?

Thx, Sliatecinos.

**Comment by XPanniX** [comment]
@sliatecinos 

I'm just hosting this repository for archiving purposes - I can't provide extensive support, sorry.

But here are some things you could try:
1. Did you run the application with administrator privileges?
2. It's possible that the driver signature expired:
    1. Try setting your computer's time to a previous year (e.g. 2012)
    2. Try booting windows with driver signature verification/enforcement turned off

**Comment by JANogueira** [comment]
Maybe this is a bit too late to answer, but for the sake of information availability, you will need to restart your windows into advanced settings menu (Going to the Settings App -> Update and Security -> Recovery -> Under Advanced startup, select Restart now).

Then:
1) After your PC restarts to the Choose an option screen, select Troubleshoot > Advanced options > Startup Settings > Restart.

2) Choose an option screen in the Windows Recovery Environment.

3) Troubleshoot screen in the Windows Recovery Environment.

4) Advanced options screen in the Windows Recovery Environment.

5) Startup Settings  screen in the Windows Recovery Environment.

6) When prompted, choose the option "Disable Driver Signature Enformcement" (Should be option 7. Hit F7. if it shows as option 5, hit F5, etc).

After this, you will be able to install the Driver successfully.

Guides:
Additional info on how to get into the recovery menu that I mentioned above, with some pictures:
https://support.microsoft.com/en-us/windows/start-your-pc-in-safe-mode-in-windows-10-92c27cff-db89-8644-1ce4-b3e5e56fe234 (Select "From Settings").

https://www.tenforums.com/tutorials/156602-how-enable-disable-driver-signature-enforcement-windows-10-a.html (Follow Option One)

**Comment by XPanniX** [comment]
Thanks for the guide, @JANogueira!  
I added it to the README: https://github.com/XPanniX/MotioninJoyOffline/blob/master/README.md#troubleshooting

As this should resolve the issue, I'll close it.

**Comment by jhonnyV-V** [comment]
I was having the same problem, but after i disable the driver signature enforcement the exe doesn't executes
it don't show errors or something it just do nothing
